name: barfly.ai
github.url: https://owen9825.github.io/barfly.ai/
description: We connect bars with good data on their patrons for better decisions
baseurl : /barfly.ai

permalink: /:title/
paginate: 100

plugins: [jekyll-paginate, jekyll-bower]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'bower.json', 'node_modules', 'package.json']
